sslfetch.connections: Format the exception instead of using addition
Avoid:

  Traceback (most recent call last):
    File "./bin/gkeys", line 42, in <module>
      from gkeys.cli import Main
    File "/.../gentoo-keys/gkeys/cli.py", line 20, in <module>
      from gkeys.actions import Actions, Available_Actions
    File "/.../gentoo-keys/gkeys/actions.py", line 22, in <module>
      from sslfetch.connections import Connector
    File "/.../ssl-fetch/sslfetch/connections.py", line 55, in <module>
      "Error was:" + e
  TypeError: cannot concatenate 'str' and 'exceptions.ImportError' objects